// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopVanPhongPham.Data;

#nullable disable

namespace ShopVanPhongPham.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606134226_UpdateProductImages")]
    partial class UpdateProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopVanPhongPham.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopVanPhongPham.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ShopVanPhongPham.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "But",
                            Description = "",
                            ImageUrl = "/assets/images/butthienlong.jpg",
                            Name = "Bút bi Thiên Long",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "But",
                            Description = "",
                            ImageUrl = "/assets/images/butchib2.jpg",
                            Name = "Bút chì 2B",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "So",
                            Description = "",
                            ImageUrl = "/assets/images/sotay.jpg",
                            Name = "Sổ tay A5",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "So",
                            Description = "",
                            ImageUrl = "/assets/images/tap200trang.jpg",
                            Name = "Tập 200 trang",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "DungCu",
                            Description = "",
                            ImageUrl = "/assets/images/thuocke30cm.jpg",
                            Name = "Thước kẻ 30cm",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "DungCu",
                            Description = "",
                            ImageUrl = "/assets/images/keovanphong1.jpg",
                            Name = "Kéo văn phòng",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "DungCu",
                            Description = "",
                            ImageUrl = "/assets/images/bamkim.jpg",
                            Name = "Bấm kim",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Giay",
                            Description = "",
                            ImageUrl = "/assets/images/giayA4.jpg",
                            Name = "Giấy A4 500 tờ",
                            Price = 85000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "DungCu",
                            Description = "",
                            ImageUrl = "/assets/images/bangkeo.png",
                            Name = "Băng keo trong",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 10,
                            Category = "DungCu",
                            Description = "",
                            ImageUrl = "/assets/images/hopbut.jpg",
                            Name = "Hộp bút để bàn",
                            Price = 45000m
                        });
                });

            modelBuilder.Entity("ShopVanPhongPham.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("ShopVanPhongPham.Models.OrderDetail", b =>
                {
                    b.HasOne("ShopVanPhongPham.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopVanPhongPham.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopVanPhongPham.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("ShopVanPhongPham.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopVanPhongPham.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
